# Tags in this file MUST match GitLab runner configured tags else the jobs will not run.
default:
  image: docker
  tags: [testing]

stages:
  - build
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  CONTAINER_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  
services:
  - docker:19.03.12-dind

before_script:
  - docker info
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

# Build an image tagged with the commit SHA
build_image:
  stage: build
  script:
    - docker build --pull --tag $CONTAINER_IMAGE .
    - docker push $CONTAINER_IMAGE
  except:
    - tags

deploy_latest:
  stage: deploy
  script:
    - docker pull $CONTAINER_IMAGE
    - docker tag $CONTAINER_IMAGE $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - master

# If the pipeline source is a tag, push an image with that tag, and 
# also push to 'latest'
deploy_tag:
  stage: deploy
  script:
    - docker pull $CONTAINER_IMAGE
    - docker tag $CONTAINER_IMAGE $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  only:
    - tags
