version: '3'

services:
  web:
    build: 
      context: ./viringo 
        #command: gunicorn --bind 0.0.0.0:5000 manage:app 
    command: python manage.py run -h 0.0.0.0
      #image: git.computecanada.ca:4567/frdr/viringo:latest
    ports:
      - "5000:5000"
        #volumes:
        #  - /:/usr/src/app/
    env_file:
      - viringo.env
